blank_issues_enabled: false
contact_links:
   - name: GitHub Action "k8s-bake" Support
     url: https://github.com/Azure/k8s-bake
     security: https://github.com/Azure/k8s-bake/blob/main/SECURITY.md
     about: Please ask and answer questions here.
