name: setting-default-labels

on:
  # Run every day at 00.00 UTC
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          
      - uses: actions/stale@v3
        name: Setting issue as idle
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is idle because it has been open for 14 days with no activity.'
          stale-issue-label: 'idle'
          days-before-stale: 14
          days-before-close: -1
          operations-per-run: 100
          exempt-issue-labels: 'backlog'
          
      - uses: actions/stale@v3
        name: Setting PR as idle
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is idle because it has been open for 14 days with no activity.'
          stale-pr-label: 'idle'
          days-before-stale: 14
          days-before-close: -1
          operations-per-run: 100