name: Check Signed Commits

on:
   pull_request:

permissions:
   contents: read
   pull-requests: write

jobs:
   signed:
      uses: Azure/action-release-workflows/.github/workflows/check_signed_commits.yaml@a391b701462581f586d0e8a68e60b04aa47dc4a9 # v1.2.0
