name: "Run unit tests."
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - master
      - 'releases/*'
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running L0 tests.
      run: |
        sudo npm install n 
        sudo n latest
        echo $(node -v)
        echo $(npm -v)
        npm install
        npm test